<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/Python/Pandas/5.handling_missing_data_replace_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**<font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/All files/weather_data1.csv")

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

**Replacing single value**

In [ ]:
df.replace(-99999,1) #only -99999 value is replacing with the 1.

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017            1          7     Sunny
2  1/3/2017           28          1      Snow
3  1/4/2017            1          7  no event
4  1/5/2017           32          1      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
df #because there is no inplace=True

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

**Replacing list with nan value**

Numpy is a library and pandas uses under it.

In [ ]:
import numpy as np
df.replace(-99999,np.nan) #replacing the -99999 value with NaN we need to use numpy library

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

Explicitly Mensioning

In [ ]:
df.replace(-99999,value=np.nan) #both are same just used the value key word argument

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

**Replacing list with single value**

In [ ]:
df.replace(to_replace=[-99999,-88888],value=0) #replacing the list of values with 0 with the key word aruments.

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017            0          7     Sunny
2  1/3/2017           28          0      Snow
3  1/4/2017            0          7  no event
4  1/5/2017           32          0      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34          0  no event

In [ ]:
# df.replace(to_replace=[-99999,-88888],1) #single to_place argument won't work but single value key word argument will work

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
df.replace([-99999,-88888],np.nan) #both values are replacing with NaN

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
df.replace(to_replace=[-99999,-88888],value=np.nan) #list of values are replaced with NaN with key word arguments

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

**Replacing per column**

In [ ]:
#we have to mention the column name as like a dictionary keys and value is replacing value(like nan,1,0)
df_new=df.replace({
    'temperature':-99999,
    'windspeed':[-99999,-88888],
    'event':'no event'
},np.nan)
df_new

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

**Replacing by using mapping**

In [ ]:
df.replace({
    -99999:np.nan #for all the -99999 in every column it will replace with NaN(observe row 3 and 4 in temparature and windspeed columns)
})

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

In [ ]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
df.replace({
    -99999:1, #replacing with 1 for all the column values who has value -99999
    -88888:np.nan, #for all -88888 values it will replace with NaN
    'no event':'Rain' #considering the no event value as Rain
})

        day  temperature  windspeed  event
0  1/1/2017           32        6.0   Rain
1  1/2/2017            1        7.0  Sunny
2  1/3/2017           28        1.0   Snow
3  1/4/2017            1        7.0   Rain
4  1/5/2017           32        1.0   Rain
5  1/6/2017           31        2.0  Sunny
6  1/6/2017           34        NaN   Rain

**Replacing list with another list**

In [ ]:
#creating a new data frame key are column names and list is values the length has to be same
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [ ]:
df_1 = pd.DataFrame({
    'score': ('exceptional','average', 'good', 'poor', 'average', 'exceptional','good'),
    'student': ('rob', 'maya', 'parthiv', 'tom', 'julian', 'erica','ranjiht')
})
df_1

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica
6         good  ranjiht

In [ ]:
#both treat like same because it has only single list with in the tuple.
df_2 = pd.DataFrame({
    'score':(['exceptional','average', 'good', 'poor', 'average', 'exceptional']),
    'student':(['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica'])
})
df_2

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [ ]:
#here the length has same but the no.of values are not equal
df_1 = pd.DataFrame({
    'score': (['exceptional','average', 'good', 'poor', 'average', 'exceptional'],['rob', 'maya', 'parthiv', 'tom', 'julian', 'ranjith'],['addakula','RANJITH','KUMAR']),
    'student': (['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica'],['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica'],['test'])
})
df_1

,score,student
0,"[exceptional, average, good, poor, average, ex...","[rob, maya, parthiv, tom, julian, erica]"
1,"[rob, maya, parthiv, tom, julian, ranjith]","[rob, maya, parthiv, tom, julian, erica]"
2,"[addakula, RANJITH, KUMAR]",[test]

In [ ]:
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [ ]:
# #converting qualitative to quatitative
# df.replace(['old_values'],['new_values'])

In [ ]:
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [ ]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4]) #replacing those old values with the new values

/tmp/ipykernel_14571/4220993038.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4]) #replacing those old values with the new values

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica

In [ ]:
df.replace(['poor', 'average', 'good', 'exceptional','exceptional'], [1,2,3,4,10])
#the 10 values won't return because 'exceptional' word is already stored with value 4 so it will return always 4

/tmp/ipykernel_14571/2708143008.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor', 'average', 'good', 'exceptional','exceptional'], [1,2,3,4,10])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica