<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Copy_of_Indian_finacial_fraud_data_kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
customer_data=pd.read_csv("/content/drive/MyDrive/Indian Financial Fraud Dataset.kaggle/Cusmtomer_data.csv")

In [4]:
customer_data.head(4)

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,13-11-2017
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,05-05-2020
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,23-08-2023
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,21-05-2018

In [5]:
cards_data=pd.read_csv('/content/drive/MyDrive/Indian Financial Fraud Dataset.kaggle/Cards_Data.csv')

In [6]:
cards_data

,Card_ID,Customer_ID,Card_Type,Card_Network,Credit_Limit,Card_Status,Contactless,Card_Mode,Issue_Date,Expiry_Date
0,CARD500001,CUST100001,Gold,RuPay,587317,Active,Yes,Physical,24-04-2021,24-04-2026
1,CARD500002,CUST100002,Silver,Visa,150720,Active,Yes,Virtual,30-06-2020,30-06-2025
2,CARD500003,CUST100003,Gold,RuPay,631005,Active,Yes,Physical,04-04-2022,04-04-2027
3,CARD500004,CUST100004,Silver,Mastercard,285015,Expired,Yes,Virtual,21-07-2020,21-07-2025
4,CARD500005,CUST100005,Gold,Mastercard,348591,Active,Yes,Physical,24-07-2024,24-07-2029
...,...,...,...,...,...,...,...,...,...,...
32452,CARD532453,CUST124997,Platinum,Visa,1161328,Active,Yes,Virtual,10-02-2019,10-02-2024
32453,CARD532454,CUST124997,Gold,RuPay,557911,Active,No,Physical,08-09-2020,08-09-2025
32454,CARD532455,CUST124998,Silver,Mastercard,265380,Active,Yes,Physical,16-06-2023,16-06-2028
32455,CARD532456,CUST124999,Classic,RuPay,144707,Active,Yes,Physical,02-11-2018,02-11-2023
32456,CARD532457,CUST125000,Platinum,Mastercard,1097473,Active,Yes,Physical,18-09-2018,18-09-2023

In [7]:
transaction_data=pd.read_csv('/content/drive/MyDrive/Indian Financial Fraud Dataset.kaggle/Transaction_Data_250k.csv')

In [8]:
transaction_data

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,03-03-2024,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,08-11-2023,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,11-01-2023,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,25-05-2023,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,22-10-2023,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,TXN1249996,CUST101141,CARD501484,MER100428,18-05-2026,03:40:22,44446.75,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Education,Odisha,Sambalpur,Haryana,Nuh
249996,TXN1249997,CUST100211,CARD500270,MER100300,26-02-2026,11:48:20,329.98,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Food Delivery,Madhya Pradesh,Bhopal,Tamil Nadu,Madurai
249997,TXN1249998,CUST120491,CARD526607,MER100194,11-05-2026,23:17:07,1533.55,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Medium,Fuel,Rajasthan,Jodhpur,Karnataka,Mangaluru
249998,TXN1249999,CUST110885,CARD514128,MER100361,19-10-2023,21:09:24,527.61,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Medium,Pharmacy,Bihar,Bhagalpur,Assam,Guwahati
249999,TXN1250000,CUST113764,CARD517861,MER100378,28-08-2025,15:51:03,1000.00,UPI,Online Web,iOS Mobile,Successful,0,0,NaN,Medium,Travel,Punjab,Ludhiana,Bihar,Gaya

In [9]:
merchant_data=pd.read_csv('/content/drive/MyDrive/Indian Financial Fraud Dataset.kaggle/merchant_table.csv')

In [10]:
merchant_data

,Merchant_ID,Merchant_Name,Merchant_Category,State,City,Merchant_Risk_Level,Merchant_Rating,Merchant_Status,Merchant_Since
0,MER100001,Paytm Utilities,Utilities,Haryana,Gurugram,Medium,4.8,Active,29-07-2012
1,MER100002,Coursera,Education,Bihar,Patna,Low,4.3,Active,09-03-2008
2,MER100003,Redbus,Travel,Bihar,Muzaffarpur,Low,4.7,Active,12-08-2006
3,MER100004,Air India,Airline,Tamil Nadu,Salem,Low,3.6,Active,30-03-2008
4,MER100005,IndiGo,Airline,Punjab,Jalandhar,Medium,4.1,Active,18-07-2007
...,...,...,...,...,...,...,...,...,...
495,MER100496,IRCTC,Travel,Assam,Silchar,Low,4.5,Active,19-04-2009
496,MER100497,Apple Store,Electronics,Madhya Pradesh,Jabalpur,Low,3.5,Active,29-08-2018
497,MER100498,Tata Cliq,Ecommerce,Bihar,Bhagalpur,Low,4.5,Active,13-10-2014
498,MER100499,Amazon Prime Video,Entertainment,Assam,Dibrugarh,High,4.7,Active,27-01-2025
499,MER100500,MakeMyTrip Hotels,Hotel,Gujarat,Bhavnagar,Medium,3.8,Active,31-01-2017

### **customer_data**

In [11]:
# dir(customer_data)

In [12]:
# output_path

No.of rows and no.of columns in the data

In [13]:
customer_data.shape

(25000, 12)

In [14]:
# customer_data.count_values

Only Age and Annual_Income columns will shows because only these are numeric columns

In [15]:
customer_data.describe()

                Age  Annual_Income
count  25000.000000   2.500000e+04
mean      41.805840   1.611153e+06
std       13.062435   1.727786e+06
min       18.000000   2.000000e+00
25%       31.000000   5.704775e+05
50%       41.000000   9.691890e+05
75%       52.000000   1.882414e+06
max       70.000000   9.999931e+06

Getting all the columns

In [16]:
customer_data.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Marital_Status',
       'Occupation', 'Annual_Income', 'Customer_Segment', 'State', 'City',
       'Account_Type', 'Customer_Since'],
      dtype='object')

In [17]:
# customer_data.customer_ID.count_values()

In [18]:
# dir(customer_data.customer_ID)

In [19]:
# help(customer_data['customer_ID'])

In [20]:
# help(pd.Series)

In [21]:
# pd.

In [22]:
display(customer_data.head())

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,13-11-2017
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,05-05-2020
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,23-08-2023
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,21-05-2018
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Rajasthan,Jodhpur,Salary,16-04-2017

The first 5 rows of `customer_data` are shown above. As you indicated in the next cell, we will now look at the number of rows and columns in the DataFrame.

# Cleaning the data

In [23]:
customer_data

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,13-11-2017
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,05-05-2020
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,23-08-2023
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,21-05-2018
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Rajasthan,Jodhpur,Salary,16-04-2017
...,...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST124996,Onveer Kala,Male,22,Single,Nurse,740591,Gold,Odisha,Rourkela,Salary,09-12-2021
24996,CUST124997,Waida Dewan,Female,29,Single,Lawyer,3033538,Platinum,Karnataka,Bengaluru,Savings,19-07-2021
24997,CUST124998,Mohini Devi,Male,48,Married,Government Employee,1364078,Gold,West Bengal,Kolkata,Salary,25-04-2020
24998,CUST124999,Rishi Bahri,Male,52,Married,Farmer,324265,Standard,Odisha,Bhubaneswar,Savings,27-12-2021
24999,CUST125000,Chanchal Sarkar,Female,32,Married,Lawyer,3000217,Platinum,Kerala,Thrissur,Salary,18-06-2020

In [24]:
#summing all the columns which has null values
customer_data.isnull().sum()

Customer_ID         0
Customer_Name       0
Gender              0
Age                 0
Marital_Status      0
Occupation          0
Annual_Income       0
Customer_Segment    0
State               0
City                0
Account_Type        0
Customer_Since      0
dtype: int64

In [25]:
customer_data.isnull().sum().sum()

np.int64(0)

In [26]:
customer_data[customer_data.notnull().all(axis=1)]

,Customer_ID,Customer_Name,Gender,Age,Marital_Status,Occupation,Annual_Income,Customer_Segment,State,City,Account_Type,Customer_Since
0,CUST100001,Omaja Majumdar,Female,27,Single,Police Officer,1167132,Gold,Uttar Pradesh,Agra,Savings,13-11-2017
1,CUST100002,Jason Agrawal,Female,41,Married,Teacher,493532,Standard,Madhya Pradesh,Ujjain,Salary,05-05-2020
2,CUST100003,Amrita Dora,Male,61,Divorsed,Business,1862614,Platinum,Assam,Silchar,Savings,23-08-2023
3,CUST100004,Radhika Batra,Male,26,Single,Software Engineer,808153,Gold,Uttar Pradesh,Ghaziabad,Salary,21-05-2018
4,CUST100005,Gautam Mukhopadhyay,Female,24,Single,Software Engineer,1581447,Platinum,Rajasthan,Jodhpur,Salary,16-04-2017
...,...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST124996,Onveer Kala,Male,22,Single,Nurse,740591,Gold,Odisha,Rourkela,Salary,09-12-2021
24996,CUST124997,Waida Dewan,Female,29,Single,Lawyer,3033538,Platinum,Karnataka,Bengaluru,Savings,19-07-2021
24997,CUST124998,Mohini Devi,Male,48,Married,Government Employee,1364078,Gold,West Bengal,Kolkata,Salary,25-04-2020
24998,CUST124999,Rishi Bahri,Male,52,Married,Farmer,324265,Standard,Odisha,Bhubaneswar,Savings,27-12-2021
24999,CUST125000,Chanchal Sarkar,Female,32,Married,Lawyer,3000217,Platinum,Kerala,Thrissur,Salary,18-06-2020

2. Count unique values in a specific column of those rows

In [27]:
customer_data[customer_data.isnull().any(axis=1)]['Customer_ID'].value_counts()

Series([], Name: count, dtype: int64)

#performing operations on a single columns

In [28]:
customer_data['Customer_ID']

0        CUST100001
1        CUST100002
2        CUST100003
3        CUST100004
4        CUST100005
            ...
24995    CUST124996
24996    CUST124997
24997    CUST124998
24998    CUST124999
24999    CUST125000
Name: Customer_ID, Length: 25000, dtype: object

In [29]:
customer_data['Customer_ID'].value_counts()

Customer_ID
CUST125000    1
CUST100001    1
CUST100002    1
CUST100003    1
CUST100004    1
             ..
CUST100013    1
CUST100012    1
CUST100011    1
CUST100010    1
CUST100009    1
Name: count, Length: 25000, dtype: int64

In [30]:
# customer_data['Customer_ID'].unique().value_counts()

In [31]:
customer_data['Customer_ID'].value_counts().sum()

np.int64(25000)

In [32]:
customer_data['Customer_ID'].unique()

array(['CUST100001', 'CUST100002', 'CUST100003', ..., 'CUST124998',
       'CUST124999', 'CUST125000'], dtype=object)

If you want the number of unique Customer_IDs

In [33]:
customer_data['Customer_ID'].nunique()

25000

In [34]:
#It is in python code
len(customer_data['Customer_ID'].unique())

25000

Performing operation on State column on customer_data

In [35]:
customer_data['State']

0         Uttar Pradesh
1        Madhya Pradesh
2                 Assam
3         Uttar Pradesh
4             Rajasthan
              ...
24995            Odisha
24996         Karnataka
24997       West Bengal
24998            Odisha
24999            Kerala
Name: State, Length: 25000, dtype: object

In [36]:
customer_data['State'].unique()

array(['Uttar Pradesh', 'Madhya Pradesh', 'Assam', 'Rajasthan', 'Haryana',
       'Maharashtra', 'West Bengal', 'Bihar', 'Punjab', 'Kerala',
       'Odisha', 'Telangana', 'Gujarat', 'Tamil Nadu', 'Karnataka'],
      dtype=object)

In [37]:
customer_data['State'].nunique()

15

In [38]:
cards_data.columns

Index(['Card_ID', 'Customer_ID', 'Card_Type', 'Card_Network', 'Credit_Limit',
       'Card_Status', 'Contactless', 'Card_Mode', 'Issue_Date', 'Expiry_Date'],
      dtype='object')

In [39]:
merchant_data.value_counts()

Merchant_ID  Merchant_Name      Merchant_Category  State           City         Merchant_Risk_Level  Merchant_Rating  Merchant_Status  Merchant_Since
MER100500    MakeMyTrip Hotels  Hotel              Gujarat         Bhavnagar    Medium               3.8              Active           31-01-2017        1
MER100001    Paytm Utilities    Utilities          Haryana         Gurugram     Medium               4.8              Active           29-07-2012        1
MER100002    Coursera           Education          Bihar           Patna        Low                  4.3              Active           09-03-2008        1
MER100003    Redbus             Travel             Bihar           Muzaffarpur  Low                  4.7              Active           12-08-2006        1
MER100484    HP Lubricants      Fuel               Bihar           Purnia       Low                  4.0              Active           09-06-2014        1
                                                                                                                                                        ..
MER100009    Udemy              Education          Assam           Nagaon       Low                  5.0              Active           17-07-2017        1
MER100008    Amazon             Ecommerce          West Bengal     Siliguri     Low                  5.0              Inactive         14-11-2018        1
MER100007    Swiggy             Food Delivery      Madhya Pradesh  Indore       Low                  4.6              Active           28-03-2023        1
MER100006    Shell Station      Fuel               Gujarat         Surat        Low                  4.5              Active           25-02-2016        1
MER100005    IndiGo             Airline            Punjab          Jalandhar    Medium               4.1              Active           18-07-2007        1
Name: count, Length: 500, dtype: int64

In [40]:
len(merchant_data.value_counts())

500

In [41]:
merchant_data['Merchant_ID'].nunique()

500

In [42]:
cards_data.value_counts()

Card_ID     Customer_ID  Card_Type  Card_Network      Credit_Limit  Card_Status  Contactless  Card_Mode  Issue_Date  Expiry_Date
CARD532457  CUST125000   Platinum   Mastercard        1097473       Active       Yes          Physical   18-09-2018  18-09-2023     1
CARD500001  CUST100001   Gold       RuPay             587317        Active       Yes          Physical   24-04-2021  24-04-2026     1
CARD500002  CUST100002   Silver     Visa              150720        Active       Yes          Virtual    30-06-2020  30-06-2025     1
CARD500003  CUST100003   Gold       RuPay             631005        Active       Yes          Physical   04-04-2022  04-04-2027     1
CARD500004  CUST100004   Silver     Mastercard        285015        Expired      Yes          Virtual    21-07-2020  21-07-2025     1
                                                                                                                                   ..
CARD500014  CUST100011   Gold       American Express  312754        Active       Yes          Virtual    24-05-2025  24-05-2030     1
CARD500013  CUST100010   Gold       Visa              639738        Expired      No           Physical   05-03-2026  05-03-2031     1
CARD500012  CUST100010   Gold       Visa              651387        Active       Yes          Physical   07-03-2024  07-03-2029     1
CARD500011  CUST100009   Silver     Mastercard        206823        Active       Yes          Physical   14-04-2019  14-04-2024     1
CARD500010  CUST100009   Platinum   Visa              971876        Active       Yes          Physical   17-07-2026  17-07-2031     1
Name: count, Length: 32457, dtype: int64

In [43]:
transaction_data.value_counts()

Transaction_ID  Customer_ID  Card_ID     Merchant_ID  Transaction_Date  Transaction_Time  Transaction_Amount  Payment_Method  Transaction_Channel  Device_Type   Transaction_Status  Is_International  Fraud_Flag  Fraud_Reason                                      Merchant_Risk_Level  Merchant_Category  Customer_State  Customer_City  Merchant_State  Merchant_City
TXN1249958      CUST104783   CARD506213  MER100351    14-03-2025        23:58:07          17791.70            Credit Card     POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Expired Card               Medium               Hospital           Uttar Pradesh   Noida          Bihar           Muzaffarpur      1
TXN1249672      CUST118660   CARD524211  MER100314    01-02-2026        21:28:37          712.63              Debit Card      ATM                  ATM Machine   Declined            0                 1           Transaction Attempt on Expired Card               Medium               Entertainment      Assam           Nagaon         Odisha          Bhubaneswar      1
TXN1249655      CUST113114   CARD516999  MER100360    19-05-2025        23:46:25          29654.51            Debit Card      POS                  POS Terminal  Successful          0                 1           Late Night Geographical & Velocity Anomaly        Low                  Hotel              Kerala          Kochi          Madhya Pradesh  Indore           1
TXN1249644      CUST114131   CARD518351  MER100078    08-05-2023        12:31:42          781.77              Credit Card     Mobile App           iOS Mobile    Failed              0                 1           Rapid Velocity & Multiple Failed Auth Attempts    Low                  Fuel               Odisha          Cuttack        Madhya Pradesh  Ujjain           1
TXN1249599      CUST114419   CARD518718  MER100375    28-07-2023        22:43:06          16113.99            Debit Card      ATM                  ATM Machine   Declined            0                 1           Transaction Attempt on Expired Card               Medium               Travel             Rajasthan       Jodhpur        Tamil Nadu      Coimbatore       1
                                                                                                                                                                                                                                                                                                                                                                            ..
TXN1000121      CUST113361   CARD517331  MER100064    17-05-2026        03:43:41          1579.30             Debit Card      POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Blocked Card               Low                  Entertainment      Maharashtra     Aurangabad     Madhya Pradesh  Jabalpur         1
TXN1000112      CUST120129   CARD526150  MER100239    07-06-2026        23:45:40          1589.10             Credit Card     POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Expired Card               Low                  Entertainment      Rajasthan       Jaipur         Odisha          Sambalpur        1
TXN1000105      CUST111877   CARD515409  MER100052    28-03-2025        00:52:39          18331.90            Credit Card     POS                  POS Terminal  Successful          0                 1           Late Night Geographical & Velocity Anomaly        Low                  Fashion            Karnataka       Mysuru         Rajasthan       Alwar            1
TXN1000072      CUST101850   CARD502409  MER100260    09-09-2023        11:32:26          10845.15            Debit Card      POS                  POS Terminal  Successful          1                 1           Unusual Cross-Border / International Transaction  Low                  Grocery            Assam           Nagaon         Gujarat         Bhavnagar        1
TXN1000066      CUST122402   CARD529063  MER100216    15-07-2023        22:40:55          4338.67             Net Banking     Online Web           iOS Mobile    Failed              0                 1           Rapid Velocity & Multiple Failed Auth Attempts    Low                  Electronics        Haryana         HOdal          Assam           Guwahati         1
Name: count, Length: 13473, dtype: int64

In [44]:
transaction_data.columns

Index(['Transaction_ID', 'Customer_ID', 'Card_ID', 'Merchant_ID',
       'Transaction_Date', 'Transaction_Time', 'Transaction_Amount',
       'Payment_Method', 'Transaction_Channel', 'Device_Type',
       'Transaction_Status', 'Is_International', 'Fraud_Flag', 'Fraud_Reason',
       'Merchant_Risk_Level', 'Merchant_Category', 'Customer_State',
       'Customer_City', 'Merchant_State', 'Merchant_City'],
      dtype='object')

In [45]:
transaction_data['Transaction_ID']

0         TXN1000001
1         TXN1000002
2         TXN1000003
3         TXN1000004
4         TXN1000005
             ...
249995    TXN1249996
249996    TXN1249997
249997    TXN1249998
249998    TXN1249999
249999    TXN1250000
Name: Transaction_ID, Length: 250000, dtype: object

In [46]:
transaction_data['Card_ID'].value_counts()

Card_ID
CARD509956    26
CARD523475    21
CARD529133    21
CARD530218    20
CARD515587    19
              ..
CARD508516     1
CARD505971     1
CARD529299     1
CARD518602     1
CARD520496     1
Name: count, Length: 32292, dtype: int64

In [47]:
cards_data['Card_ID'].value_counts()

Card_ID
CARD532457    1
CARD500001    1
CARD500002    1
CARD500003    1
CARD500004    1
             ..
CARD500014    1
CARD500013    1
CARD500012    1
CARD500011    1
CARD500010    1
Name: count, Length: 32457, dtype: int64

In [48]:
cards_data['Card_ID'].nunique()

32457

In [49]:
transaction_data.value_counts()

Transaction_ID  Customer_ID  Card_ID     Merchant_ID  Transaction_Date  Transaction_Time  Transaction_Amount  Payment_Method  Transaction_Channel  Device_Type   Transaction_Status  Is_International  Fraud_Flag  Fraud_Reason                                      Merchant_Risk_Level  Merchant_Category  Customer_State  Customer_City  Merchant_State  Merchant_City
TXN1249958      CUST104783   CARD506213  MER100351    14-03-2025        23:58:07          17791.70            Credit Card     POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Expired Card               Medium               Hospital           Uttar Pradesh   Noida          Bihar           Muzaffarpur      1
TXN1249672      CUST118660   CARD524211  MER100314    01-02-2026        21:28:37          712.63              Debit Card      ATM                  ATM Machine   Declined            0                 1           Transaction Attempt on Expired Card               Medium               Entertainment      Assam           Nagaon         Odisha          Bhubaneswar      1
TXN1249655      CUST113114   CARD516999  MER100360    19-05-2025        23:46:25          29654.51            Debit Card      POS                  POS Terminal  Successful          0                 1           Late Night Geographical & Velocity Anomaly        Low                  Hotel              Kerala          Kochi          Madhya Pradesh  Indore           1
TXN1249644      CUST114131   CARD518351  MER100078    08-05-2023        12:31:42          781.77              Credit Card     Mobile App           iOS Mobile    Failed              0                 1           Rapid Velocity & Multiple Failed Auth Attempts    Low                  Fuel               Odisha          Cuttack        Madhya Pradesh  Ujjain           1
TXN1249599      CUST114419   CARD518718  MER100375    28-07-2023        22:43:06          16113.99            Debit Card      ATM                  ATM Machine   Declined            0                 1           Transaction Attempt on Expired Card               Medium               Travel             Rajasthan       Jodhpur        Tamil Nadu      Coimbatore       1
                                                                                                                                                                                                                                                                                                                                                                            ..
TXN1000121      CUST113361   CARD517331  MER100064    17-05-2026        03:43:41          1579.30             Debit Card      POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Blocked Card               Low                  Entertainment      Maharashtra     Aurangabad     Madhya Pradesh  Jabalpur         1
TXN1000112      CUST120129   CARD526150  MER100239    07-06-2026        23:45:40          1589.10             Credit Card     POS                  POS Terminal  Declined            0                 1           Transaction Attempt on Expired Card               Low                  Entertainment      Rajasthan       Jaipur         Odisha          Sambalpur        1
TXN1000105      CUST111877   CARD515409  MER100052    28-03-2025        00:52:39          18331.90            Credit Card     POS                  POS Terminal  Successful          0                 1           Late Night Geographical & Velocity Anomaly        Low                  Fashion            Karnataka       Mysuru         Rajasthan       Alwar            1
TXN1000072      CUST101850   CARD502409  MER100260    09-09-2023        11:32:26          10845.15            Debit Card      POS                  POS Terminal  Successful          1                 1           Unusual Cross-Border / International Transaction  Low                  Grocery            Assam           Nagaon         Gujarat         Bhavnagar        1
TXN1000066      CUST122402   CARD529063  MER100216    15-07-2023        22:40:55          4338.67             Net Banking     Online Web           iOS Mobile    Failed              0                 1           Rapid Velocity & Multiple Failed Auth Attempts    Low                  Electronics        Haryana         HOdal          Assam           Guwahati         1
Name: count, Length: 13473, dtype: int64

In [50]:
transaction_data['Transaction_ID'].value_counts()

Transaction_ID
TXN1249984    1
TXN1249983    1
TXN1249982    1
TXN1249981    1
TXN1249980    1
             ..
TXN1000005    1
TXN1000004    1
TXN1000003    1
TXN1000002    1
TXN1000001    1
Name: count, Length: 250000, dtype: int64

In [51]:
transaction_data

,Transaction_ID,Customer_ID,Card_ID,Merchant_ID,Transaction_Date,Transaction_Time,Transaction_Amount,Payment_Method,Transaction_Channel,Device_Type,Transaction_Status,Is_International,Fraud_Flag,Fraud_Reason,Merchant_Risk_Level,Merchant_Category,Customer_State,Customer_City,Merchant_State,Merchant_City
0,TXN1000001,CUST100660,CARD500875,MER100380,03-03-2024,05:50:10,21748.02,Debit Card,Mobile App,Android Mobile,Successful,1,0,NaN,Low,Hotel,Tamil Nadu,Madurai,Tamil Nadu,Salem
1,TXN1000002,CUST111388,CARD514772,MER100017,08-11-2023,06:55:15,9960.60,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Travel,Kerala,Kollam,Haryana,Nuh
2,TXN1000003,CUST115872,CARD520625,MER100143,11-01-2023,02:17:28,838.61,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Food Delivery,Uttar Pradesh,Agra,West Bengal,Kolkata
3,TXN1000004,CUST109049,CARD511773,MER100053,25-05-2023,01:48:56,52694.99,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Financial Services,Punjab,Ludhiana,Madhya Pradesh,Indore
4,TXN1000005,CUST114459,CARD518771,MER100064,22-10-2023,00:23:32,1043.40,Debit Card,Online Web,Android Mobile,Successful,0,0,NaN,Low,Entertainment,Maharashtra,Thane,Madhya Pradesh,Jabalpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,TXN1249996,CUST101141,CARD501484,MER100428,18-05-2026,03:40:22,44446.75,Debit Card,ATM,ATM Machine,Successful,0,0,NaN,Low,Education,Odisha,Sambalpur,Haryana,Nuh
249996,TXN1249997,CUST100211,CARD500270,MER100300,26-02-2026,11:48:20,329.98,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Low,Food Delivery,Madhya Pradesh,Bhopal,Tamil Nadu,Madurai
249997,TXN1249998,CUST120491,CARD526607,MER100194,11-05-2026,23:17:07,1533.55,Debit Card,POS,POS Terminal,Successful,0,0,NaN,Medium,Fuel,Rajasthan,Jodhpur,Karnataka,Mangaluru
249998,TXN1249999,CUST110885,CARD514128,MER100361,19-10-2023,21:09:24,527.61,Credit Card,POS,POS Terminal,Successful,0,0,NaN,Medium,Pharmacy,Bihar,Bhagalpur,Assam,Guwahati
249999,TXN1250000,CUST113764,CARD517861,MER100378,28-08-2025,15:51:03,1000.00,UPI,Online Web,iOS Mobile,Successful,0,0,NaN,Medium,Travel,Punjab,Ludhiana,Bihar,Gaya

In [52]:
transaction_data['Transaction_ID'].nunique()

250000

In [53]:
transaction_data.isnull().sum()

Transaction_ID              0
Customer_ID                 0
Card_ID                     0
Merchant_ID                 0
Transaction_Date            0
Transaction_Time            0
Transaction_Amount          0
Payment_Method              0
Transaction_Channel         0
Device_Type                 0
Transaction_Status          0
Is_International            0
Fraud_Flag                  0
Fraud_Reason           236527
Merchant_Risk_Level         0
Merchant_Category           0
Customer_State              0
Customer_City               0
Merchant_State              0
Merchant_City               0
dtype: int64

In [54]:
transaction_data.columns

Index(['Transaction_ID', 'Customer_ID', 'Card_ID', 'Merchant_ID',
       'Transaction_Date', 'Transaction_Time', 'Transaction_Amount',
       'Payment_Method', 'Transaction_Channel', 'Device_Type',
       'Transaction_Status', 'Is_International', 'Fraud_Flag', 'Fraud_Reason',
       'Merchant_Risk_Level', 'Merchant_Category', 'Customer_State',
       'Customer_City', 'Merchant_State', 'Merchant_City'],
      dtype='object')

In [55]:
transaction_data.columns.nunique()

20

NO.of Unique values in the columns

In [56]:
transaction_data.nunique()

Transaction_ID         250000
Customer_ID             24902
Card_ID                 32292
Merchant_ID               500
Transaction_Date         1325
Transaction_Time        81562
Transaction_Amount     178189
Payment_Method              4
Transaction_Channel         4
Device_Type                 6
Transaction_Status          3
Is_International            2
Fraud_Flag                  2
Fraud_Reason                8
Merchant_Risk_Level         3
Merchant_Category          15
Customer_State             15
Customer_City              85
Merchant_State             15
Merchant_City              85
dtype: int64

In [57]:
transaction_data['Merchant_Risk_Level'].value_counts()

Merchant_Risk_Level
Low       154896
Medium     64366
High       30738
Name: count, dtype: int64

In [58]:
transaction_data['Merchant_Risk_Level'].max()

'Medium'

In [59]:
transaction_data['Transaction_Status'].value_counts()

Transaction_Status
Successful    227821
Declined       12010
Failed         10169
Name: count, dtype: int64