<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Lotus%20Retail%20Dataset%20-%20Power%20BI%20(Multi%20tables)/Uncleaned/dim_cust.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np

In [3]:
dim_cust=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_customers.csv')

In [4]:
dim_cust.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [5]:
dim_cust.shape

(3050, 10)

In [6]:
dim_cust.isnull()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False,False,False
3049,False,False,False,False,False,True,False,False,False,False

In [7]:
dim_cust.columns

Index(['customer_id', 'full_name', 'gender', 'birth_date', 'phone', 'email',
       'city', 'region', 'loyalty_tier', 'registration_date'],
      dtype='object')

In [8]:
dim_cust.describe()

              phone
count  3.050000e+03
mean   1.154291e+09
std    8.475046e+07
min    1.010092e+09
25%    1.077888e+09
50%    1.153491e+09
75%    1.229041e+09
max    1.299995e+09

In [9]:
dim_cust.isnull().sum()

customer_id            0
full_name              0
gender                 0
birth_date             0
phone                  0
email                382
city                   0
region                 0
loyalty_tier           0
registration_date      0
dtype: int64

In [10]:
dim_cust['email']

0       mohamed.mansour52@hotmail.com
1                                 NaN
2           ahmed.hafez18@outlook.com
3            hoda.fathy26@outlook.com
4           hussein.lotfy80@gmail.com
                    ...
3045          walid.ali72@outlook.com
3046            ola.gamal66@yahoo.com
3047         sara.gamal56@hotmail.com
3048      youssef.nasser5@hotmail.com
3049                              NaN
Name: email, Length: 3050, dtype: object

In [11]:
dim_cust['email'].isnull()

0       False
1        True
2       False
3       False
4       False
        ...
3045    False
3046    False
3047    False
3048    False
3049     True
Name: email, Length: 3050, dtype: bool

In [12]:
print(dim_cust['email'].isnull().sum())

382

There are 385 records of null values in the email column and there is no null values in the other columns

In [13]:
missing = dim_cust['email'].isna() #selecting the Nan indexes in the data frame

print(type(missing))
print(missing.head())

<class 'pandas.core.series.Series'>
0    False
1     True
2    False
3    False
4    False
Name: email, dtype: bool

In [14]:
print(dim_cust.loc[missing, 'email']) #selecting the missing indexes and email

1       NaN
24      NaN
28      NaN
30      NaN
35      NaN
       ...
3004    NaN
3010    NaN
3011    NaN
3019    NaN
3049    NaN
Name: email, Length: 382, dtype: object

In [15]:
print(dim_cust.index[missing])

Index([   1,   24,   28,   30,   35,   47,   51,   60,   82,  110,
       ...
       2937, 2939, 2962, 2974, 2986, 3004, 3010, 3011, 3019, 3049],
      dtype='int64', length=382)

In [16]:
dim_cust.loc[missing, 'full_name'] #selecting missing indexes and full_name column

1          Maged Lotfy
24         Tarek Lotfy
28          Omar Ahmed
30          Ahmed Zaki
35        Sherif Hamdy
             ...
3004      Sherif Wahba
3010    Hassan Mansour
3011       Sara Khalil
3019       Hossam Zaki
3049      Samah Khalil
Name: full_name, Length: 382, dtype: object

In [17]:
dim_cust.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [18]:
missing = dim_cust['email'].isna() #storing missing values in 'missing' object like in data record 2 it true

random_numbers = pd.Series(
    np.random.randint(0, 100, size=missing.sum()), #np.random.randint(start, stop, size) here there are 382 missing records
    index=dim_cust.index[missing] #select only missing indexes of the data frame eg.0,1,2,3,4,5,6,7...only 1,3,7 indexes are missing the email(i.e has Nan values) then it will only select those indexes Index([1, 3, 7]).
).astype(str).str.zfill(2) #converting into string datpe because to append and str.zfill(2) it make every number only 2 string digit

dim_cust.loc[missing, 'email'] = (    #loc is used to select the row and columns  and Select the email column only where missing == True.
    dim_cust.loc[missing, 'full_name']
        .str.strip() #removing the spaces like first and last spaces
        .str.lower() #converting them into lower case
        .str.replace(r'\s+', '.', regex=True) #r'\s+' (Find one or more whitespace characters.)
                                    #replacing space with '.(dot)' and + used for one or more white spaces like('Ranjith  Addakula) there are two space then it will give(ranjith.addakula)
    + random_numbers #adding the above object
    + '@outlook.com' #adding the fixed domain
)

In [19]:
print(dim_cust[['full_name', 'email']].head(5).to_string(index=False))

      full_name                         email
Mohamed Mansour mohamed.mansour52@hotmail.com
    Maged Lotfy     maged.lotfy88@outlook.com
    Ahmed Hafez     ahmed.hafez18@outlook.com
     Hoda Fathy      hoda.fathy26@outlook.com
  Hussein Lotfy     hussein.lotfy80@gmail.com

In [20]:
dim_cust

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,maged.lotfy88@outlook.com,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,samah.khalil22@outlook.com,Hurghada,Red Sea,Bronze,2020-09-23