<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Lotus%20Retail%20Dataset%20-%20Power%20BI%20(Multi%20tables)/Uncleaned/dim_cust.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np

In [27]:
dim_cust=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_customers.csv')

In [28]:
dim_cust.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [29]:
dim_cust.shape

(3050, 10)

In [30]:
dim_cust.isnull()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False,False,False
3049,False,False,False,False,False,True,False,False,False,False

In [31]:
dim_cust.columns

Index(['customer_id', 'full_name', 'gender', 'birth_date', 'phone', 'email',
       'city', 'region', 'loyalty_tier', 'registration_date'],
      dtype='object')

In [32]:
dim_cust.describe()

              phone
count  3.050000e+03
mean   1.154291e+09
std    8.475046e+07
min    1.010092e+09
25%    1.077888e+09
50%    1.153491e+09
75%    1.229041e+09
max    1.299995e+09

In [33]:
dim_cust.isnull().sum()

customer_id            0
full_name              0
gender                 0
birth_date             0
phone                  0
email                382
city                   0
region                 0
loyalty_tier           0
registration_date      0
dtype: int64

In [34]:
dim_cust['email']

0       mohamed.mansour52@hotmail.com
1                                 NaN
2           ahmed.hafez18@outlook.com
3            hoda.fathy26@outlook.com
4           hussein.lotfy80@gmail.com
                    ...
3045          walid.ali72@outlook.com
3046            ola.gamal66@yahoo.com
3047         sara.gamal56@hotmail.com
3048      youssef.nasser5@hotmail.com
3049                              NaN
Name: email, Length: 3050, dtype: object

In [35]:
dim_cust['email'].isnull()

0       False
1        True
2       False
3       False
4       False
        ...
3045    False
3046    False
3047    False
3048    False
3049     True
Name: email, Length: 3050, dtype: bool