<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Lotus%20Retail%20Dataset%20-%20Power%20BI%20(Multi%20tables)/Copy_of_dim_cust.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [203]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [204]:
import pandas as pd
import numpy as np

In [205]:
dim_cust=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_customers.csv')

In [206]:
dim_cust.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [207]:
dim_cust.shape

(3050, 10)

In [208]:
dim_cust.isnull()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False,False,False
3049,False,False,False,False,False,True,False,False,False,False

In [209]:
dim_cust.columns

Index(['customer_id', 'full_name', 'gender', 'birth_date', 'phone', 'email',
       'city', 'region', 'loyalty_tier', 'registration_date'],
      dtype='object')

In [210]:
dim_cust.describe()

              phone
count  3.050000e+03
mean   1.154291e+09
std    8.475046e+07
min    1.010092e+09
25%    1.077888e+09
50%    1.153491e+09
75%    1.229041e+09
max    1.299995e+09

In [211]:
dim_cust.isnull().sum()

customer_id            0
full_name              0
gender                 0
birth_date             0
phone                  0
email                382
city                   0
region                 0
loyalty_tier           0
registration_date      0
dtype: int64

In [212]:
dim_cust['email']

0       mohamed.mansour52@hotmail.com
1                                 NaN
2           ahmed.hafez18@outlook.com
3            hoda.fathy26@outlook.com
4           hussein.lotfy80@gmail.com
                    ...
3045          walid.ali72@outlook.com
3046            ola.gamal66@yahoo.com
3047         sara.gamal56@hotmail.com
3048      youssef.nasser5@hotmail.com
3049                              NaN
Name: email, Length: 3050, dtype: object

In [213]:
dim_cust['email'].isnull()

0       False
1        True
2       False
3       False
4       False
        ...
3045    False
3046    False
3047    False
3048    False
3049     True
Name: email, Length: 3050, dtype: bool

In [214]:
print(dim_cust['email'].isnull().sum())

382

There are 385 records of null values in the email column and there is no null values in the other columns

In [215]:
missing = dim_cust['email'].isna() #selecting the Nan indexes in the data frame

print(type(missing))
print(missing.head())

<class 'pandas.core.series.Series'>
0    False
1     True
2    False
3    False
4    False
Name: email, dtype: bool

In [216]:
print(dim_cust.loc[missing, 'email']) #selecting the missing indexes and email

1       NaN
24      NaN
28      NaN
30      NaN
35      NaN
       ...
3004    NaN
3010    NaN
3011    NaN
3019    NaN
3049    NaN
Name: email, Length: 382, dtype: object

In [217]:
print(dim_cust.index[missing])

Index([   1,   24,   28,   30,   35,   47,   51,   60,   82,  110,
       ...
       2937, 2939, 2962, 2974, 2986, 3004, 3010, 3011, 3019, 3049],
      dtype='int64', length=382)

In [218]:
dim_cust.loc[missing, 'full_name'] #selecting missing indexes and full_name column

1          Maged Lotfy
24         Tarek Lotfy
28          Omar Ahmed
30          Ahmed Zaki
35        Sherif Hamdy
             ...
3004      Sherif Wahba
3010    Hassan Mansour
3011       Sara Khalil
3019       Hossam Zaki
3049      Samah Khalil
Name: full_name, Length: 382, dtype: object

In [219]:
dim_cust.head()

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05

In [220]:
missing = dim_cust['email'].isna() #storing missing values in 'missing' object like in data record 2 it true

random_numbers = pd.Series(
    np.random.randint(0, 100, size=missing.sum()), #np.random.randint(start, stop, size) here there are 382 missing records
    index=dim_cust.index[missing] #select only missing indexes of the data frame eg.0,1,2,3,4,5,6,7...only 1,3,7 indexes are missing the email(i.e has Nan values) then it will only select those indexes Index([1, 3, 7]).
).astype(str).str.zfill(2) #converting into string datpe because to append and str.zfill(2) it make every number only 2 string digit

dim_cust.loc[missing, 'email'] = (    #loc is used to select the row and columns  and Select the email column only where missing == True.
    dim_cust.loc[missing, 'full_name'] #take the full_name values from rows where missing is True, and put them into the email column of those same rows
        .str.strip() #removing the spaces like first and last spaces
        .str.lower() #converting them into lower case
        .str.replace(r'\s+', '.', regex=True) #r'\s+' (Find one or more whitespace characters.)
                                    #replacing space with '.(dot)' and + used for one or more white spaces like('Ranjith  Addakula) there are two space then it will give(ranjith.addakula)
    + random_numbers #adding the above object
    + '@outlook.com' #adding the fixed domain
)

In [221]:
print(dim_cust[['full_name', 'email']].head(5).to_string(index=False))

      full_name                         email
Mohamed Mansour mohamed.mansour52@hotmail.com
    Maged Lotfy     maged.lotfy79@outlook.com
    Ahmed Hafez     ahmed.hafez18@outlook.com
     Hoda Fathy      hoda.fathy26@outlook.com
  Hussein Lotfy     hussein.lotfy80@gmail.com

In [222]:
print(dim_cust[['full_name', 'email']].head(50).to_string(index=False))

      full_name                         email
Mohamed Mansour mohamed.mansour52@hotmail.com
    Maged Lotfy     maged.lotfy79@outlook.com
    Ahmed Hafez     ahmed.hafez18@outlook.com
     Hoda Fathy      hoda.fathy26@outlook.com
  Hussein Lotfy     hussein.lotfy80@gmail.com
   Nour Mostafa    nour.mostafa72@hotmail.com
    Hazem Hamdy     hazem.hamdy68@outlook.com
 Fatima Ramadan  fatima.ramadan42@outlook.com
    Ramy Farouk      ramy.farouk8@hotmail.com
    Sherif Zaki      sherif.zaki7@hotmail.com
  Bassem Farouk     bassem.farouk40@gmail.com
   Hossam Fathy      hossam.fathy16@yahoo.com
    Hoda Badawi       hoda.badawi40@yahoo.com
  Ahmed Mostafa   ahmed.mostafa83@hotmail.com
  Yasmin Khalil     yasmin.khalil15@gmail.com
 Hussein Younis    hussein.younis30@yahoo.com
   Ramy Ramadan      ramy.ramadan58@yahoo.com
   Doha Shaaban      doha.shaaban46@gmail.com
    Tarek Ragab       tarek.ragab11@gmail.com
   Ibrahim Bakr     ibrahim.bakr8@outlook.com
     Salma Zaki      salma.zaki23@hotmail.com
       Ramy Ali        ramy.ali33@hotmail.com
    Hany Khalil     hany.khalil59@outlook.com
     Engy Attia        engy.attia68@yahoo.com
    Tarek Lotfy     tarek.lotfy84@outlook.com
      Nour Bakr       nour.bakr54@hotmail.com
   Ramy Mansour    ramy.mansour11@hotmail.com
Yasmin Abdallah   yasmin.abdallah68@gmail.com
     Omar Ahmed      omar.ahmed04@outlook.com
 Hussein Hassan  hussein.hassan95@hotmail.com
     Ahmed Zaki      ahmed.zaki16@outlook.com
    Rana Ismail       rana.ismail64@gmail.com
      Amr Salem         amr.salem38@yahoo.com
     Fady Lotfy        fady.lotfy20@gmail.com
     Dina Attia        dina.attia61@yahoo.com
   Sherif Hamdy    sherif.hamdy39@outlook.com
   Nadia Badawi      nadia.badawi95@yahoo.com
  Ibrahim Hamdy   ibrahim.hamdy27@outlook.com
  Manar Ibrahim   manar.ibrahim47@hotmail.com
    Hoda Younis      hoda.younis8@hotmail.com
    Hana Badawi       hana.badawi79@yahoo.com
    Rania Ahmed       rania.ahmed91@gmail.com
     Heba Lotfy        heba.lotfy31@yahoo.com
    Essam Salem       essam.salem29@yahoo.com
    Dalia Gamal       dalia.gamal68@gmail.com
    Ghada Gouda       ghada.gouda76@gmail.com
   Doha Ramadan    doha.ramadan87@hotmail.com
     Adel Hamdy      adel.hamdy32@outlook.com
     Engy Gouda        engy.gouda79@gmail.com
   Zeinab Wahba    zeinab.wahba56@outlook.com

In [223]:
dim_cust['email']

0       mohamed.mansour52@hotmail.com
1           maged.lotfy79@outlook.com
2           ahmed.hafez18@outlook.com
3            hoda.fathy26@outlook.com
4           hussein.lotfy80@gmail.com
                    ...
3045          walid.ali72@outlook.com
3046            ola.gamal66@yahoo.com
3047         sara.gamal56@hotmail.com
3048      youssef.nasser5@hotmail.com
3049       samah.khalil03@outlook.com
Name: email, Length: 3050, dtype: object

In [224]:
dim_cust

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,maged.lotfy79@outlook.com,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,samah.khalil03@outlook.com,Hurghada,Red Sea,Bronze,2020-09-23

# Selecting email domain

In [225]:
dim_cust['email']

0       mohamed.mansour52@hotmail.com
1           maged.lotfy79@outlook.com
2           ahmed.hafez18@outlook.com
3            hoda.fathy26@outlook.com
4           hussein.lotfy80@gmail.com
                    ...
3045          walid.ali72@outlook.com
3046            ola.gamal66@yahoo.com
3047         sara.gamal56@hotmail.com
3048      youssef.nasser5@hotmail.com
3049       samah.khalil03@outlook.com
Name: email, Length: 3050, dtype: object

In [226]:
dim_cust['email'].str.split('@').str[-1].nunique()

4

In [227]:
dim_cust['email'].str.split('@').str[-1].dropna().unique()

array(['hotmail.com', 'outlook.com', 'gmail.com', 'yahoo.com'],
      dtype=object)

In [228]:
df=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_customers.csv')

In [229]:
df

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,NaN,Hurghada,Red Sea,Bronze,2020-09-23

In [230]:
df['email'].str.split('@').str[-1].nunique()

4

In [231]:
l=df['email'].str.split('@').str[-1].dropna().unique()
l

array(['hotmail.com', 'outlook.com', 'gmail.com', 'yahoo.com'],
      dtype=object)

In [232]:
df

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,NaN,Hurghada,Red Sea,Bronze,2020-09-23

In [233]:
import numpy as np

missing = df['email'].isna()

domains = np.random.choice(
    ['hotmail.com', 'outlook.com', 'gmail.com', 'yahoo.com'],
    size=missing.sum()
)

random_numbers = np.random.randint(0, 100, size=missing.sum())

df.loc[missing, 'email'] = (
    df.loc[missing, 'full_name']
    .str.lower()
    .str.replace(' ', '.', regex=False)
    + np.char.zfill(random_numbers.astype(str), 2)
    + '@'
    + domains
)

In [234]:
df

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,maged.lotfy96@gmail.com,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,samah.khalil66@hotmail.com,Hurghada,Red Sea,Bronze,2020-09-23

In [235]:
df_cust=pd.read_csv('/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_customers.csv')

In [236]:
df_cust

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,NaN,Hurghada,Red Sea,Bronze,2020-09-23

In [237]:
# import numpy as np

# missing = df_cust['email'].isna()

# domains = np.random.choice(
#     ['hotmail.com', 'outlook.com', 'gmail.com', 'yahoo.com'],
#     size=missing.sum()
# )

# phone_digits = df_cust.loc[missing, 'phone'].astype(str).apply(
#     lambda x: ''.join(np.random.choice(list(set(x)), 2, replace=False))
# )

# df_cust.loc[missing, 'email'] = (
#     df_cust.loc[missing, 'full_name']
#     .str.lower()
#     .str.replace(' ', '.', regex=False)
#     + phone_digits
#     + '@'
#     + domains
# )

In [238]:
df_cust

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,NaN,Hurghada,Red Sea,Bronze,2020-09-23

In [239]:
df_cust['customer_id'].duplicated().any()

np.True_

In [240]:
df_cust[df_cust['customer_id'].duplicated()]

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
432,CUS02610,Ahmed Mostafa,MALE,1974-03-02,1063360110,ahmed.mostafa95@outlook.com,Cairo,Greater Cairo,Bronze,2022-03-14
541,CUS00044,Adel Bakr,Male,1978-03-24,1195800828,adel.bakr89@hotmail.com,Suez,Canal Zone,Gold,2021-11-19
807,CUS01993,Dalia Hamdy,Female,16/04/1993,1189684093,dalia.hamdy84@hotmail.com,Mansoura,Nile Delta,Bronze,2023-01-19
810,CUS01175,Youssef Younis,Male,1985-07-06,1267278051,youssef.younis95@yahoo.com,Mansoura,Nile Delta,Platinum,2020-03-27
926,CUS01721,Mariam Nasser,Female,1996-01-23,1190808054,mariam.nasser90@yahoo.com,Cairo,Greater Cairo,Silver,2022-07-08
956,CUS02224,Aisha Hafez,Female,1972-09-27,1225073447,aisha.hafez91@yahoo.com,Cairo,Greater Cairo,Silver,2022-11-17
1143,CUS02233,Ashraf Amin,male,1975-03-16,1140963485,ashraf.amin91@hotmail.com,Suez,Canal Zone,Gold,2022-11-16
1250,CUS02214,Radwa Lotfy,Female,1998-07-13,1148451635,radwa.lotfy21@gmail.com,Ismailia,Canal Zone,Bronze,2023-10-09
1346,CUS02855,Hany Saad,Male,1996-02-12,1215604302,NaN,Cairo,Greater Cairo,Bronze,2021-10-05
1357,CUS00899,Ramy Ibrahim,male,2003-04-27,1073753876,ramy.ibrahim13@hotmail.com,Cairo,Greater Cairo,Bronze,2022-11-19
1428,CUS02462,Omar Mohamed,Male,1972-10-19,1185032591,omar.mohamed73@yahoo.com,Suez,Canal Zone,Bronze,2020-07-21
1507,CUS00793,Samir Saad,Male,1981-07-25,1073516387,samir.saad83@yahoo.com,Alexandria,Alexandria,Gold,2023-04-23
1559,CUS02655,Essam Ali,Male,1970-03-12,1086793020,essam.ali40@hotmail.com,Hurghada,Red Sea,Gold,2023-01-20
1580,CUS00105,Hoda Salem,Female,1993-07-08,1249057246,hoda.salem2@yahoo.com,Suez,Canal Zone,Bronze,2021-09-05
1581,CUS02311,Ahmed Khalil,Male,1985-07-05,1217827726,ahmed.khalil89@hotmail.com,Alexandria,Alexandria,Bronze,2021-02-04
1631,CUS02645,Walid Khalil,Male,09/06/1977,1056761054,walid.khalil8@outlook.com,Cairo,Greater Cairo,Bronze,2020-11-05
1641,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
1681,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17
1722,CUS01260,Eman Younis,Female,1978-04-10,1198562616,eman.younis87@outlook.com,Alexandria,Alexandria,Bronze,2022-06-28
1750,CUS00859,Emad Mansour,Male,1991-06-09,1134502256,emad.mansour46@hotmail.com,Alexandria,Alexandria,Silver,2021-11-08
1772,CUS02051,Samir Lotfy,Male,26/11/1992,1265446571,samir.lotfy43@hotmail.com,Giza,Greater Cairo,Bronze,2023-12-07
1824,CUS00731,Akram Younis,Male,2001-02-14,1214149208,akram.younis99@gmail.com,Cairo,Greater Cairo,Bronze,2022-05-13
1843,CUS02382,Nour Abdallah,Female,1993-12-01,1221482568,nour.abdallah82@hotmail.com,Luxor,Upper Egypt,Bronze,2023-06-05
1909,CUS02806,Samir Shaaban,male,06/08/1972,1155695129,samir.shaaban93@hotmail.com,Ismailia,Canal Zone,Silver,2023-07-02
1939,CUS00579,Adel Ali,MALE,1977-06-24,1081305655,NaN,Alexandria,Alexandria,Bronze,2021-11-16
1977,CUS02910,Mona Mohamed,FEMALE,1975-11-24,1140195198,mona.mohamed1@outlook.com,Giza,Greater Cairo,Bronze,2021-05-09
1996,CUS00032,Shaimaa Sayed,Female,1983-09-08,1176038997,shaimaa.sayed6@yahoo.com,Cairo,Greater Cairo,Bronze,2023-12-12
2029,CUS02698,Salma Abdallah,female,1996-11-03,1139615919,salma.abdallah99@yahoo.com,Giza,Greater Cairo,Bronze,2023-02-12
2069,CUS01929,Rania Fathy,Female,2001-05-17,1147869930,rania.fathy80@hotmail.com,Mansoura,Nile Delta,Bronze,2022-04-18
2107,CUS02036,Suzy Ibrahim,Female,26/11/1973,1251984383,suzy.ibrahim25@outlook.com,Giza,Greater Cairo,Bronze,2021-02-05
2132,CUS02053,Zeinab Bakr,Female,1996-01-02,1240691047,zeinab.bakr51@hotmail.com,Cairo,Greater Cairo,Bronze,2022-11-05
2162,CUS02863,Ramy Ramadan,Male,1989-05-22,1019329244,ramy.ramadan58@yahoo.com,Port Said,Canal Zone,Platinum,2023-04-19
2180,CUS02467,Dina Bakr,FEMALE,1986-05-25,1184306405,dina.bakr7@outlook.com,Giza,Greater Cairo,Bronze,2020-06-28
2295,CUS00360,Heba Lotfy,Female,1989-08-02,1210626224,heba.lotfy31@yahoo.com,Alexandria,Alexandria,Bronze,2020-01-14
2357,CUS00803,Ayman Salem,male,1974-03-16,1111023114,ayman.salem54@gmail.com,Alexandria,Alexandria,Bronze,2020-03-07
2445,CUS01395,Hany Rizk,male,1990-02-21,1118218152,hany.rizk55@gmail.com,Giza,Greater Cairo,Silver,2021-01-26
2464,CUS02865,Mohamed Ismail,Male,1993-08-05,1260507167,mohamed.ismail12@gmail.com,Giza,Greater Cairo,Bronze,2023-12-16
2529,CUS01549,Radwa Badawi,Female,1995-11-08,1136567299,radwa.badawi46@outlook.com,Cairo,Greater Cairo,Bronze,2020-08-02
2544,CUS01650,Ali Mahmoud,Male,1977-11-25,1217433350,NaN,Tanta,Nile Delta,Bronze,2023-04-18
2557,CUS02445,Nadia Amin,Female,1982-02-16,1231347320,nadia.amin79@outlook.com,Giza,Greater Cairo,Bronze,2023-07-05
2698,CUS02094,Rana Rizk,female,1990-12-07,1013450881,rana.rizk31@outlook.com,Alexandria,Alexandria,Bronze,2023-03-10
2701,CUS01246,Khaled Barakat,Male,1975-11-21,1145699484,NaN,Mansoura,Nile Delta,Silver,2021-10-02
2720,CUS01114,Aisha Saad,Female,1989-12-27,1173680989,aisha.saad54@hotmail.com,Alexandria,Alexandria,Gold,2022-02-08
2733,CUS00164,Dina Lotfy,Female,2003-11-20,1240524866,dina.lotfy78@hotmail.com,Alexandria,Alexandria,Bronze,2023-09-05
2740,CUS02668,Adel Hafez,Male,25/09/1993,1166835720,NaN,Mansoura,Nile Delta,Bronze,2021-07-17
2858,CUS00684,Hassan Mansour,MALE,1975-12-03,1068112164,NaN,Mansoura,Nile Delta,Bronze,2022-11-17
2940,CUS01699,Aisha Mahmoud,Female,1980-07-19,1217115675,aisha.mahmoud75@hotmail.com,Ismailia,Canal Zone,Bronze,2021-12-09
2958,CUS02265,Ahmed Bakr,Male,2003-01-04,1085431973,ahmed.bakr77@outlook.com,Mansoura,Nile Delta,Bronze,2022-05-16
3011,CUS01736,Sara Khalil,Female,1988-09-20,1157278097,NaN,Suez,Canal Zone,Silver,2023-03-08
3013,CUS02484,Sherif Younis,male,20/09/1980,1075866125,sherif.younis75@yahoo.com,Cairo,Greater Cairo,Silver,2020-10-26

In [241]:
df_cust['customer_id'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3045    False
3046    False
3047    False
3048    False
3049    False
Name: customer_id, Length: 3050, dtype: bool

In [242]:
df_cust['customer_id'].duplicated().sum()

np.int64(50)

In [243]:
df_cust['customer_id'].value_counts().loc[lambda x: x > 1]

customer_id
CUS02910    2
CUS02036    2
CUS02668    2
CUS02855    2
CUS00360    2
CUS01114    2
CUS00859    2
CUS02467    2
CUS02224    2
CUS02698    2
CUS02957    2
CUS02214    2
CUS00793    2
CUS01246    2
CUS02445    2
CUS01260    2
CUS02233    2
CUS02462    2
CUS01699    2
CUS02265    2
CUS01395    2
CUS02865    2
CUS01650    2
CUS01736    2
CUS02655    2
CUS02645    2
CUS01721    2
CUS00001    2
CUS02484    2
CUS00105    2
CUS02382    2
CUS00044    2
CUS00164    2
CUS00579    2
CUS01993    2
CUS00731    2
CUS01929    2
CUS00803    2
CUS02610    2
CUS02053    2
CUS02094    2
CUS02051    2
CUS02863    2
CUS02311    2
CUS02806    2
CUS01175    2
CUS01549    2
CUS00684    2
CUS00032    2
CUS00899    2
Name: count, dtype: int64

In [244]:
df=df_cust[df_cust['customer_id'].duplicated(keep=False)]

In [245]:
df

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
16,CUS02863,Ramy Ramadan,Male,1989-05-22,1019329244,ramy.ramadan58@yahoo.com,Port Said,Canal Zone,Platinum,2023-04-19
42,CUS00360,Heba Lotfy,Female,1989-08-02,1210626224,heba.lotfy31@yahoo.com,Alexandria,Alexandria,Bronze,2020-01-14
72,CUS02445,Nadia Amin,Female,1982-02-16,1231347320,nadia.amin79@outlook.com,Giza,Greater Cairo,Bronze,2023-07-05
108,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
165,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17
...,...,...,...,...,...,...,...,...,...,...
2858,CUS00684,Hassan Mansour,MALE,1975-12-03,1068112164,NaN,Mansoura,Nile Delta,Bronze,2022-11-17
2940,CUS01699,Aisha Mahmoud,Female,1980-07-19,1217115675,aisha.mahmoud75@hotmail.com,Ismailia,Canal Zone,Bronze,2021-12-09
2958,CUS02265,Ahmed Bakr,Male,2003-01-04,1085431973,ahmed.bakr77@outlook.com,Mansoura,Nile Delta,Bronze,2022-05-16
3011,CUS01736,Sara Khalil,Female,1988-09-20,1157278097,NaN,Suez,Canal Zone,Silver,2023-03-08
3013,CUS02484,Sherif Younis,male,20/09/1980,1075866125,sherif.younis75@yahoo.com,Cairo,Greater Cairo,Silver,2020-10-26

In [246]:
df=df_cust[df_cust['customer_id'].duplicated(keep=False)] \
.sort_values('customer_id')

In [247]:
duplicates = df_cust[df_cust['customer_id'].duplicated(keep=False)] \
               .sort_values('customer_id')

In [248]:
duplicates

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
108,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
1641,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
577,CUS00032,Shaimaa Sayed,Female,1983-09-08,1176038997,shaimaa.sayed6@yahoo.com,Cairo,Greater Cairo,Bronze,2023-12-12
1996,CUS00032,Shaimaa Sayed,Female,1983-09-08,1176038997,shaimaa.sayed6@yahoo.com,Cairo,Greater Cairo,Bronze,2023-12-12
460,CUS00044,Adel Bakr,Male,1978-03-24,1195800828,adel.bakr89@hotmail.com,Suez,Canal Zone,Gold,2021-11-19
...,...,...,...,...,...,...,...,...,...,...
2464,CUS02865,Mohamed Ismail,Male,1993-08-05,1260507167,mohamed.ismail12@gmail.com,Giza,Greater Cairo,Bronze,2023-12-16
1977,CUS02910,Mona Mohamed,FEMALE,1975-11-24,1140195198,mona.mohamed1@outlook.com,Giza,Greater Cairo,Bronze,2021-05-09
184,CUS02910,Mona Mohamed,FEMALE,1975-11-24,1140195198,mona.mohamed1@outlook.com,Giza,Greater Cairo,Bronze,2021-05-09
1681,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17
165,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17

In [249]:
duplicates.value_counts() #does not count the NaN values

customer_id  full_name       gender  birth_date  phone       email                        city        region         loyalty_tier  registration_date
CUS00001     Manar Hamdy     Female  1977-10-07  1283233096  manar.hamdy91@yahoo.com      Giza        Greater Cairo  Silver        2023-05-27           2
CUS00032     Shaimaa Sayed   Female  1983-09-08  1176038997  shaimaa.sayed6@yahoo.com     Cairo       Greater Cairo  Bronze        2023-12-12           2
CUS00044     Adel Bakr       Male    1978-03-24  1195800828  adel.bakr89@hotmail.com      Suez        Canal Zone     Gold          2021-11-19           2
CUS00105     Hoda Salem      Female  1993-07-08  1249057246  hoda.salem2@yahoo.com        Suez        Canal Zone     Bronze        2021-09-05           2
CUS00164     Dina Lotfy      Female  2003-11-20  1240524866  dina.lotfy78@hotmail.com     Alexandria  Alexandria     Bronze        2023-09-05           2
CUS00360     Heba Lotfy      Female  1989-08-02  1210626224  heba.lotfy31@yahoo.com       Alexandria  Alexandria     Bronze        2020-01-14           2
CUS00731     Akram Younis    Male    2001-02-14  1214149208  akram.younis99@gmail.com     Cairo       Greater Cairo  Bronze        2022-05-13           2
CUS00793     Samir Saad      Male    1981-07-25  1073516387  samir.saad83@yahoo.com       Alexandria  Alexandria     Gold          2023-04-23           2
CUS00803     Ayman Salem     male    1974-03-16  1111023114  ayman.salem54@gmail.com      Alexandria  Alexandria     Bronze        2020-03-07           2
CUS00859     Emad Mansour    Male    1991-06-09  1134502256  emad.mansour46@hotmail.com   Alexandria  Alexandria     Silver        2021-11-08           2
CUS00899     Ramy Ibrahim    male    2003-04-27  1073753876  ramy.ibrahim13@hotmail.com   Cairo       Greater Cairo  Bronze        2022-11-19           2
CUS01114     Aisha Saad      Female  1989-12-27  1173680989  aisha.saad54@hotmail.com     Alexandria  Alexandria     Gold          2022-02-08           2
CUS01175     Youssef Younis  Male    1985-07-06  1267278051  youssef.younis95@yahoo.com   Mansoura    Nile Delta     Platinum      2020-03-27           2
CUS01260     Eman Younis     Female  1978-04-10  1198562616  eman.younis87@outlook.com    Alexandria  Alexandria     Bronze        2022-06-28           2
CUS01395     Hany Rizk       male    1990-02-21  1118218152  hany.rizk55@gmail.com        Giza        Greater Cairo  Silver        2021-01-26           2
CUS01549     Radwa Badawi    Female  1995-11-08  1136567299  radwa.badawi46@outlook.com   Cairo       Greater Cairo  Bronze        2020-08-02           2
CUS01699     Aisha Mahmoud   Female  1980-07-19  1217115675  aisha.mahmoud75@hotmail.com  Ismailia    Canal Zone     Bronze        2021-12-09           2
CUS01721     Mariam Nasser   Female  1996-01-23  1190808054  mariam.nasser90@yahoo.com    Cairo       Greater Cairo  Silver        2022-07-08           2
CUS01929     Rania Fathy     Female  2001-05-17  1147869930  rania.fathy80@hotmail.com    Mansoura    Nile Delta     Bronze        2022-04-18           2
CUS01993     Dalia Hamdy     Female  16/04/1993  1189684093  dalia.hamdy84@hotmail.com    Mansoura    Nile Delta     Bronze        2023-01-19           2
CUS02036     Suzy Ibrahim    Female  26/11/1973  1251984383  suzy.ibrahim25@outlook.com   Giza        Greater Cairo  Bronze        2021-02-05           2
CUS02051     Samir Lotfy     Male    26/11/1992  1265446571  samir.lotfy43@hotmail.com    Giza        Greater Cairo  Bronze        2023-12-07           2
CUS02053     Zeinab Bakr     Female  1996-01-02  1240691047  zeinab.bakr51@hotmail.com    Cairo       Greater Cairo  Bronze        2022-11-05           2
CUS02094     Rana Rizk       female  1990-12-07  1013450881  rana.rizk31@outlook.com      Alexandria  Alexandria     Bronze        2023-03-10           2
CUS02214     Radwa Lotfy     Female  1998-07-13  1148451635  radwa.lotfy21@gmail.com      Ismailia    Canal Zone     Bronze        2023-10-09           2
CUS02224     Aisha Hafez     Female  1972-09-27  1225073447  aisha.hafez91@yahoo.com      Cairo       Greater Cairo  Silver        2022-11-17           2
CUS02233     Ashraf Amin     male    1975-03-16  1140963485  ashraf.amin91@hotmail.com    Suez        Canal Zone     Gold          2022-11-16           2
CUS02265     Ahmed Bakr      Male    2003-01-04  1085431973  ahmed.bakr77@outlook.com     Mansoura    Nile Delta     Bronze        2022-05-16           2
CUS02311     Ahmed Khalil    Male    1985-07-05  1217827726  ahmed.khalil89@hotmail.com   Alexandria  Alexandria     Bronze        2021-02-04           2
CUS02382     Nour Abdallah   Female  1993-12-01  1221482568  nour.abdallah82@hotmail.com  Luxor       Upper Egypt    Bronze        2023-06-05           2
CUS02445     Nadia Amin      Female  1982-02-16  1231347320  nadia.amin79@outlook.com     Giza        Greater Cairo  Bronze        2023-07-05           2
CUS02462     Omar Mohamed    Male    1972-10-19  1185032591  omar.mohamed73@yahoo.com     Suez        Canal Zone     Bronze        2020-07-21           2
CUS02467     Dina Bakr       FEMALE  1986-05-25  1184306405  dina.bakr7@outlook.com       Giza        Greater Cairo  Bronze        2020-06-28           2
CUS02484     Sherif Younis   male    20/09/1980  1075866125  sherif.younis75@yahoo.com    Cairo       Greater Cairo  Silver        2020-10-26           2
CUS02610     Ahmed Mostafa   MALE    1974-03-02  1063360110  ahmed.mostafa95@outlook.com  Cairo       Greater Cairo  Bronze        2022-03-14           2
CUS02645     Walid Khalil    Male    09/06/1977  1056761054  walid.khalil8@outlook.com    Cairo       Greater Cairo  Bronze        2020-11-05           2
CUS02655     Essam Ali       Male    1970-03-12  1086793020  essam.ali40@hotmail.com      Hurghada    Red Sea        Gold          2023-01-20           2
CUS02698     Salma Abdallah  female  1996-11-03  1139615919  salma.abdallah99@yahoo.com   Giza        Greater Cairo  Bronze        2023-02-12           2
CUS02806     Samir Shaaban   male    06/08/1972  1155695129  samir.shaaban93@hotmail.com  Ismailia    Canal Zone     Silver        2023-07-02           2
CUS02863     Ramy Ramadan    Male    1989-05-22  1019329244  ramy.ramadan58@yahoo.com     Port Said   Canal Zone     Platinum      2023-04-19           2
CUS02865     Mohamed Ismail  Male    1993-08-05  1260507167  mohamed.ismail12@gmail.com   Giza        Greater Cairo  Bronze        2023-12-16           2
CUS02910     Mona Mohamed    FEMALE  1975-11-24  1140195198  mona.mohamed1@outlook.com    Giza        Greater Cairo  Bronze        2021-05-09           2
Name: count, dtype: int64

In [250]:
duplicates.sort_values('customer_id', na_position='last')

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
108,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
1641,CUS00001,Manar Hamdy,Female,1977-10-07,1283233096,manar.hamdy91@yahoo.com,Giza,Greater Cairo,Silver,2023-05-27
577,CUS00032,Shaimaa Sayed,Female,1983-09-08,1176038997,shaimaa.sayed6@yahoo.com,Cairo,Greater Cairo,Bronze,2023-12-12
1996,CUS00032,Shaimaa Sayed,Female,1983-09-08,1176038997,shaimaa.sayed6@yahoo.com,Cairo,Greater Cairo,Bronze,2023-12-12
460,CUS00044,Adel Bakr,Male,1978-03-24,1195800828,adel.bakr89@hotmail.com,Suez,Canal Zone,Gold,2021-11-19
...,...,...,...,...,...,...,...,...,...,...
2464,CUS02865,Mohamed Ismail,Male,1993-08-05,1260507167,mohamed.ismail12@gmail.com,Giza,Greater Cairo,Bronze,2023-12-16
1977,CUS02910,Mona Mohamed,FEMALE,1975-11-24,1140195198,mona.mohamed1@outlook.com,Giza,Greater Cairo,Bronze,2021-05-09
184,CUS02910,Mona Mohamed,FEMALE,1975-11-24,1140195198,mona.mohamed1@outlook.com,Giza,Greater Cairo,Bronze,2021-05-09
1681,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17
165,CUS02957,Samir Mohamed,Male,1987-03-04,1011264861,NaN,Zagazig,Nile Delta,Bronze,2023-08-17

In [251]:
duplicates['customer_id'].value_counts(dropna=False).sort_index()

customer_id
CUS00001    2
CUS00032    2
CUS00044    2
CUS00105    2
CUS00164    2
CUS00360    2
CUS00579    2
CUS00684    2
CUS00731    2
CUS00793    2
CUS00803    2
CUS00859    2
CUS00899    2
CUS01114    2
CUS01175    2
CUS01246    2
CUS01260    2
CUS01395    2
CUS01549    2
CUS01650    2
CUS01699    2
CUS01721    2
CUS01736    2
CUS01929    2
CUS01993    2
CUS02036    2
CUS02051    2
CUS02053    2
CUS02094    2
CUS02214    2
CUS02224    2
CUS02233    2
CUS02265    2
CUS02311    2
CUS02382    2
CUS02445    2
CUS02462    2
CUS02467    2
CUS02484    2
CUS02610    2
CUS02645    2
CUS02655    2
CUS02668    2
CUS02698    2
CUS02806    2
CUS02855    2
CUS02863    2
CUS02865    2
CUS02910    2
CUS02957    2
Name: count, dtype: int64

In [252]:
df_cust=df_cust.drop_duplicates(subset=['customer_id'], keep='first')

In [253]:
df_cust

,customer_id,full_name,gender,birth_date,phone,email,city,region,loyalty_tier,registration_date
0,CUS01518,Mohamed Mansour,Male,1981-05-01,1158132110,mohamed.mansour52@hotmail.com,Suez,Canal Zone,Bronze,2020-12-19
1,CUS02370,Maged Lotfy,Male,2003-04-10,1281872177,NaN,Zagazig,Nile Delta,Bronze,2021-05-13
2,CUS01962,Ahmed Hafez,Male,1971-05-03,1141856715,ahmed.hafez18@outlook.com,Giza,Greater Cairo,Gold,2023-09-26
3,CUS00344,Hoda Fathy,Female,2000-05-19,1195645083,hoda.fathy26@outlook.com,Giza,Greater Cairo,Bronze,2021-07-07
4,CUS02664,Hussein Lotfy,MALE,1998-12-26,1149528740,hussein.lotfy80@gmail.com,Tanta,Nile Delta,Bronze,2022-10-05
...,...,...,...,...,...,...,...,...,...,...
3045,CUS01639,Walid Ali,Male,1994-05-01,1047701601,walid.ali72@outlook.com,Sharm El Sheikh,South Sinai,Silver,2022-09-09
3046,CUS01096,Ola Gamal,Female,1977-02-13,1143030893,ola.gamal66@yahoo.com,Cairo,Greater Cairo,Bronze,2023-08-06
3047,CUS01131,Sara Gamal,Female,1975-03-01,1245499509,sara.gamal56@hotmail.com,Zagazig,Nile Delta,Bronze,2021-12-25
3048,CUS01295,Youssef Nasser,Male,1976-06-11,1194842464,youssef.nasser5@hotmail.com,Hurghada,Red Sea,Silver,2021-11-03
3049,CUS00861,Samah Khalil,Female,1980-07-19,1039832632,NaN,Hurghada,Red Sea,Bronze,2020-09-23

In [254]:
from google.colab import files

df_cust.to_csv('dim_cust_final.csv', index=False)
files.download('dim_cust_final.csv')