<a href="https://colab.research.google.com/github/Addakularanjith123/Practice-sql/blob/main/kaggle_data/Lotus%20Retail%20Dataset%20-%20Power%20BI%20(Multi%20tables)/dim_employee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

orders = pd.read_csv("/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/fact_final_orders.csv")
employees = pd.read_csv("/content/drive/MyDrive/Kaggle datasets/Lotus Retail Dataset - Power BI (Multi tables)/dim_employees.csv")

missing_ids = orders[
    ~orders['employee_id'].isin(employees['employee_id'])
]

missing_ids[['employee_id']]

      employee_id
19            NaN
75            NaN
81            NaN
112           NaN
162           NaN
...           ...
11861         NaN
11895         NaN
11929         NaN
11971         NaN
11982         NaN

[632 rows x 1 columns]

In [5]:
missing_ids['employee_id'].drop_duplicates()

19    NaN
Name: employee_id, dtype: object

In [6]:
orders[orders['employee_id'].isna()]

,order_id,order_date,date_id,customer_id,store_id,employee_id,payment_method,order_status,total_revenue,total_cost
19,ORD0009755,2022-01-02,20220102,CUS00200,7,NaN,Credit Card,Completed,960.5,560.0
75,ORD0009837,2022-01-07,20220107,CUS00485,13,NaN,Vodafone Cash,Completed,935.0,560.0
81,ORD0007912,2022-01-07,20220107,CUS00133,7,NaN,Debit Card,Completed,3210.5,1610.0
112,ORD0001830,2022-01-11,20220111,CUS01008,5,NaN,Fawry,Completed,2232.0,1150.0
162,ORD0004082,2022-01-15,20220115,CUS00157,10,NaN,Fawry,Completed,16228.0,12620.0
...,...,...,...,...,...,...,...,...,...,...
11861,ORD0002973,2024-12-18,20241218,CUS00846,11,NaN,Debit Card,Completed,2242.0,1330.0
11895,ORD0009091,2024-12-21,20241221,CUS01184,3,NaN,Vodafone Cash,Cancelled,150.0,70.0
11929,ORD0008805,2024-12-25,20241225,CUS00826,15,NaN,Fawry,Completed,5865.0,4940.0
11971,ORD0001301,2024-12-29,20241229,CUS01886,1,NaN,Credit Card,Completed,368.0,220.0
11982,ORD0008918,2024-12-30,20241230,CUS01015,15,NaN,Cash,Completed,686.0,480.0

In [7]:
print(orders['employee_id'].dtype)
print(employees['employee_id'].dtype)

object
object

In [8]:
orders['employee_id'] = orders['employee_id'].astype('string').str.strip()
employees['employee_id'] = employees['employee_id'].astype('string').str.strip()

missing_ids = orders[
    ~orders['employee_id'].isin(employees['employee_id'])
]

missing_ids[['employee_id']].drop_duplicates()

   employee_id
19        <NA>

In [9]:
~orders['employee_id'].isin(employees['employee_id'])

0        False
1        False
2        False
3        False
4        False
         ...
11995    False
11996    False
11997    False
11998    False
11999    False
Name: employee_id, Length: 12000, dtype: bool

In [10]:
orders['employee_id'].isna().sum()

np.int64(632)

In [11]:
orders[orders['employee_id'].isna()]

,order_id,order_date,date_id,customer_id,store_id,employee_id,payment_method,order_status,total_revenue,total_cost
19,ORD0009755,2022-01-02,20220102,CUS00200,7,<NA>,Credit Card,Completed,960.5,560.0
75,ORD0009837,2022-01-07,20220107,CUS00485,13,<NA>,Vodafone Cash,Completed,935.0,560.0
81,ORD0007912,2022-01-07,20220107,CUS00133,7,<NA>,Debit Card,Completed,3210.5,1610.0
112,ORD0001830,2022-01-11,20220111,CUS01008,5,<NA>,Fawry,Completed,2232.0,1150.0
162,ORD0004082,2022-01-15,20220115,CUS00157,10,<NA>,Fawry,Completed,16228.0,12620.0
...,...,...,...,...,...,...,...,...,...,...
11861,ORD0002973,2024-12-18,20241218,CUS00846,11,<NA>,Debit Card,Completed,2242.0,1330.0
11895,ORD0009091,2024-12-21,20241221,CUS01184,3,<NA>,Vodafone Cash,Cancelled,150.0,70.0
11929,ORD0008805,2024-12-25,20241225,CUS00826,15,<NA>,Fawry,Completed,5865.0,4940.0
11971,ORD0001301,2024-12-29,20241229,CUS01886,1,<NA>,Credit Card,Completed,368.0,220.0
11982,ORD0008918,2024-12-30,20241230,CUS01015,15,<NA>,Cash,Completed,686.0,480.0